# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  checkTag:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      lastTag: ${{ steps.lastTag.outputs.var }}
      tagActual: ${{ steps.tagActual.outputs.var }}
    steps:
    - id: lastTag
      run: |
        echo "::set-output name=var::$(curl "https://api.github.com/repos/BilelJegham/RepoRelease/releases/latest" | grep -oP '(?<="tag_name": ")[^"]*' )"   
    - id: tagActual
      run: echo "::set-output name=var::beta3"
       #cat package.json | grep version| head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]'

  job2:
    runs-on: ubuntu-latest
    needs: checkTag
    if: ${{ needs.checkTag.outputs.lastTag }}  != ${{ needs.checkTag.outputs.tagActual }}
    steps:
    - run: echo ${{needs.checkTag.outputs.lastTag}} ${{needs.checkTag.outputs.tagActual}}
